# Generated by Django 4.1.7 on 2023-02-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='celuar',
            field=models.CharField(default='', max_length=11),
        ),
    ]
